sonar.projectKey=stocknova-api
sonar.projectName=StockNova API
sonar.projectVersion=1.0.0

sonar.sources=src/
sonar.tests=tests/
sonar.language=cs

sonar.exclusions=**/Migrations/**,**/obj/**,**/bin/**,**/wwwroot/**
sonar.test.exclusions=tests/**

sonar.cs.vscoveragexml.reportsPaths=coverage.xml
